### PR TITLE
Ignore dictionary types from HaveElementAt

### LINKED ISSUE #44: Dictionary access incorrectly triggers CollectionShouldHaveElementAt suggestion
I'm using FluentAssertions version 5.4.0 and FluentAssertions.Analyzers version 0.10.1. When I create a test that asserts the values in dictionaries, the analyzer incorrectly suggests I use `HaveElementAt` which doesn't compile, i.e. given this code:

``` c#
[Fact]
public void DictionaryTest()
{
    var dictionary = new Dictionary<string, int> { ["123"] = 123 };
    dictionary["123"].Should().Be(123);
}
```

The analyzer incorrectly suggests:

```c#
[Fact]
public void DictionaryTest()
{
    var dictionary = new Dictionary<string, int> { ["123"] = 123 };
    dictionary.Should().HaveElementAt("123", 123);
}
```

Perhaps it could suggest (though it's not simplifying but is more idiomatic):

``` c#
dictionary.Should().ContainKey("123").WhichValue.Should().Be(123);
```

Happy to take a stab at a PR

### PR DESCRIPTION
**Pull request by samcragg**
This fixes #44 (thanks for the pointer of where to fix it!)

### CODE REVIEW

File: src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs [hunk 1]
```diff
@@ -27,6 +28,16 @@ protected override IEnumerable<FluentAssertionsCSharpSyntaxVisitor> Visitors
             }
         }
 
+        protected override bool ShouldAnalyzeVariableType(ITypeSymbol type)
+        {
+            if (type.AllInterfaces.Any(@interface => @interface.Name == "IReadOnlyDictionary" || @interface.Name == "IDictionary"))
```
Comment (Meir017) [inline src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs]: Since the dictionary assertions are on the type `IDictionary` I think this should not look for the readonly one

File: src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs [hunk 2]
```diff
@@ -414,6 +414,14 @@ public class CollectionTests
         [Implemented]
         public void CollectionShouldNotBeNullOrEmpty_TestCodeFix(string oldAssertion, string newAssertion) => VerifyCSharpFixCodeBlock<CollectionShouldNotBeNullOrEmptyCodeFix, CollectionShouldNotBeNullOrEmptyAnalyzer>(oldAssertion, newAssertion);
 
+        [TestMethod]
+        [Implemented]
+        public void CollectionShouldHaveElementAt_ShouldIgnoreDictionaryTypes()
```
Comment (Meir017) [inline src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs]: I think this should be in the sanity tests and linked to its github issue

File: src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs [hunk 3]
```diff
@@ -27,6 +28,16 @@ protected override IEnumerable<FluentAssertionsCSharpSyntaxVisitor> Visitors
             }
         }
 
+        protected override bool ShouldAnalyzeVariableType(ITypeSymbol type)
```
Comment (Meir017) [inline src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs]: Can we move this to the collection analyzer without breaking tests?

File: src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs (hunk 1 above)
Comment (samcragg) [reply src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs]: That's correct, however, this is preventing the HaveIndexAt one from incorrectly firing on dictionaries. Since IDictionary doesn't inherit IReadOnlyDictionary I've done two checks (I use IReadOnlyDictionary in my interfaces which is where I found the bug).

File: src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs (hunk 2 above)
Comment (samcragg) [reply src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs]: Not a problem, didn't see that file 🙂
